import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, sendEmailVerification, reload } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, collection, getDocs, addDoc, query, orderBy, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAIydfYnvkcKVai2m6Zl7LjnsXiQnT0PMk",authDomain:"meet-react-dd136.firebaseapp.com",projectId:"meet-react-dd136",storageBucket:"meet-react-dd136.firebasestorage.app",messagingSenderId:"902511777751",appId:"1:902511777751:web:514ffef33e30d704575d92",measurementId:"G-X3SEF0W2N5"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let currentUser=null,currentProfile=null,view="home",nearbyUsers=[],messages=[];
const interestsList=["musica","montagna","caffè","aperitivo","moda","sport","viaggi","cinema","arte","moto","palestra","cucina","natura","ballo","lettura","metal detecting"];
const stickers=[["☕","Caffè insieme?"],["🍹","Drink?"],["🔥","Sei tanta roba"],["👋","Sono qui vicino"],["💬","Parliamo due minuti?"],["🚶","Due passi?"]];
const content=document.getElementById("content"),authBtn=document.getElementById("authBtn");
window.showView=v=>{view=v;render();};
authBtn.onclick=async()=>{if(currentUser){await signOut(auth);toast("Logout effettuato")}else showLogin();};

onAuthStateChanged(auth,async user=>{
 currentUser=user; authBtn.textContent=user?"Esci":"Login";
 if(user){try{await loadOrCreateProfile();await updateMyLocation(false);await loadNearbyUsers();await loadMessages();}catch(e){console.error(e);toast("Firebase: "+cleanError(e.message));}}
 else{currentProfile=null;nearbyUsers=[];messages=[];}
 render();
});

function defaultProfile(){return{uid:currentUser.uid,email:currentUser.email,emailVerified:currentUser.emailVerified,name:"",age:"",bio:"",photo:"",interests:[],verified:false,visible:true,profileComplete:false,lat:null,lng:null,updatedAt:Date.now()};}
async function loadOrCreateProfile(){const ref=doc(db,"users",currentUser.uid),snap=await getDoc(ref);if(snap.exists())currentProfile={...defaultProfile(),...snap.data(),emailVerified:currentUser.emailVerified};else{currentProfile=defaultProfile();await setDoc(ref,currentProfile);}}
async function saveProfileToFirebase(){if(currentUser&&currentProfile)await setDoc(doc(db,"users",currentUser.uid),currentProfile,{merge:true});}
async function updateMyLocation(showMsg=true){if(!currentUser||!currentProfile)return;if(!navigator.geolocation){if(showMsg)toast("GPS non supportato");return;}navigator.geolocation.getCurrentPosition(async pos=>{currentProfile.lat=pos.coords.latitude;currentProfile.lng=pos.coords.longitude;currentProfile.updatedAt=Date.now();await saveProfileToFirebase();await loadNearbyUsers();render();if(showMsg)toast("Posizione aggiornata");},()=>{if(showMsg)toast("Permetti il GPS per vedere persone vicine");},{enableHighAccuracy:true,timeout:10000});}
async function loadNearbyUsers(){nearbyUsers=[];if(!currentUser||!currentProfile||!currentProfile.lat||!currentProfile.lng)return;const qs=await getDocs(collection(db,"users"));qs.forEach(d=>{const u=d.data();if(!u.uid||u.uid===currentUser.uid||!u.profileComplete||u.visible===false||!u.lat||!u.lng)return;const distance=getDistanceMeters(currentProfile.lat,currentProfile.lng,u.lat,u.lng);if(distance<=300)nearbyUsers.push({...u,distance:Math.round(distance)});});nearbyUsers.sort((a,b)=>a.distance-b.distance);}
async function loadMessages(){messages=[];try{const qs=await getDocs(query(collection(db,"messages"),orderBy("createdAt")));qs.forEach(d=>messages.push(d.data()));}catch(e){console.warn(e);}}
function render(){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.remove("active"));const nav=document.getElementById("nav-"+view);if(nav)nav.classList.add("active");if(!currentUser){content.innerHTML=welcomeView();return;}if(view==="home")content.innerHTML=homeView();if(view==="stickers")content.innerHTML=stickersView();if(view==="chat")content.innerHTML=chatView();if(view==="profile")content.innerHTML=profileView();if(view==="menu")content.innerHTML=menuView();}
function welcomeView(){return `<div class="card"><h2>Benvenuto su Meet & React</h2><p class="bio">Accedi o registrati. Dopo la registrazione riceverai una mail di verifica.</p><button class="btn primary" onclick="showLogin()">Login / Registrati</button></div>`;}
window.showLogin=function(){content.innerHTML=`<div class="card"><h2>Login / Registrazione</h2><input class="input" id="email" placeholder="Email vera" type="email"><input class="input" id="password" placeholder="Password minimo 6 caratteri" type="password"><div class="grid2"><button class="btn primary" onclick="login()">Accedi</button><button class="btn" onclick="register()">Registrati</button></div><p class="small">Prima volta: Registrati. Poi apri la mail di verifica e rientra con Accedi.</p></div>`;}
window.login=async function(){try{await signInWithEmailAndPassword(auth,val("email"),val("password"));await reload(auth.currentUser);if(!auth.currentUser.emailVerified){toast("Email non verificata. Controlla la posta.");showVerifyEmailView();return;}toast("Login riuscito");view="home";render();}catch(e){toast("Errore login: "+cleanError(e.message));}}
window.register=async function(){try{const cred=await createUserWithEmailAndPassword(auth,val("email"),val("password"));await sendEmailVerification(cred.user);toast("Registrazione fatta. Controlla la mail.");showVerifyEmailView();}catch(e){toast("Errore registrazione: "+cleanError(e.message));}}
function showVerifyEmailView(){content.innerHTML=`<div class="card"><h2>Verifica la tua email</h2><p class="bio">Ti abbiamo inviato una mail di conferma. Aprila e clicca il link di verifica.</p><button class="btn primary" onclick="checkEmailVerified()">Ho verificato</button><button class="btn" onclick="resendVerification()">Reinvia email</button></div>`;}
window.checkEmailVerified=async function(){if(!auth.currentUser)return;await reload(auth.currentUser);if(auth.currentUser.emailVerified){toast("Email verificata");await loadOrCreateProfile();view="profile";render();}else toast("Email ancora non verificata");}
window.resendVerification=async function(){if(!auth.currentUser)return;await sendEmailVerification(auth.currentUser);toast("Email di verifica reinviata");}
function homeView(){if(!currentUser.emailVerified)return `<div class="notice">Devi verificare la mail prima di usare l'app.</div><div class="card"><h2>Email non verificata</h2><button class="btn primary" onclick="checkEmailVerified()">Ho verificato</button><button class="btn" onclick="resendVerification()">Reinvia email</button></div>`;if(!currentProfile||!currentProfile.profileComplete)return `<div class="notice">Prima completa il profilo. Solo utenti con nome, foto e interessi possono comparire agli altri.</div><div class="card"><h2>Completa il profilo</h2><p class="bio">Inserisci nome, età, foto e almeno un interesse.</p><button class="btn primary" onclick="showView('profile')">Vai al profilo</button></div>`;return `<div class="notice">📍 Nessun profilo finto: qui compaiono solo utenti reali entro 300 metri.</div><button class="btn green" onclick="refreshLocation()">Aggiorna posizione GPS</button><h2 class="section-title">Persone vicine</h2>${nearbyUsers.length?nearbyUsers.map(userCard).join(""):`<div class="card"><h2>Nessun utente vicino</h2><p class="bio">Per testare: apri l'app su un secondo telefono, registrati, completa il profilo e autorizza il GPS.</p></div>`}`;}
function userCard(u){const common=(u.interests||[]).filter(i=>(currentProfile.interests||[]).includes(i));return `<div class="card profile-preview"><div class="avatar">${u.photo?`<img src="${u.photo}">`:"🙂"}</div><div><h2 class="name">${esc(u.name)}${u.age?", "+esc(u.age):""}</h2><p class="meta">📍 ${u.distance} m • 🟢 In zona</p><p class="bio">${esc(u.bio||"")}</p>${u.verified?`<span class="badge">✅ Verificato</span>`:""}<div class="chips">${(u.interests||[]).map(i=>`<span class="chip">${esc(i)}</span>`).join("")}</div><p class="common">🔥 ${common.length} interessi in comune</p><div class="grid2"><button class="btn primary" onclick="sendSticker('${u.uid}','☕ Caffè insieme?')">☕ Caffè</button><button class="btn" onclick="sendSticker('${u.uid}','🔥 Sei tanta roba')">🔥 Sticker</button></div></div></div>`;}
function profileView(){if(!currentUser.emailVerified)return `<div class="notice">Verifica la mail prima di completare il profilo.</div><div class="card"><h2>Email non verificata</h2><button class="btn primary" onclick="checkEmailVerified()">Ho verificato</button><button class="btn" onclick="resendVerification()">Reinvia email</button></div>`;const p=currentProfile||defaultProfile();return `<h2 class="section-title">Il mio profilo</h2><div class="card"><div class="profile-head"><div class="avatar-large" id="photoPreview">${p.photo?`<img src="${p.photo}">`:"🙂"}</div><div><h2>Foto profilo</h2><p class="bio">Usa una foto reale del viso.</p><label class="file-label">📸 Carica foto<input type="file" accept="image/*" onchange="loadPhoto(event)"></label></div></div><input class="input" id="pname" placeholder="Nome" value="${esc(p.name)}"><input class="input" id="page" placeholder="Età" inputmode="numeric" value="${esc(p.age)}"><textarea id="pbio" placeholder="Bio breve">${esc(p.bio)}</textarea><h3>Interessi</h3><div class="chips">${interestsList.map(i=>`<label class="chip-check"><input type="checkbox" value="${i}" ${(p.interests||[]).includes(i)?"checked":""}><span>${i}</span></label>`).join("")}</div><button class="btn primary" onclick="saveProfile()">Salva profilo reale</button><button class="btn green" onclick="verifyPhoto()">Simula verifica foto</button></div>`;}
window.loadPhoto=function(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=function(e){if(!currentProfile)currentProfile=defaultProfile();currentProfile.photo=e.target.result;const el=document.getElementById("photoPreview");if(el)el.innerHTML=`<img src="${currentProfile.photo}">`;toast("Foto caricata");};reader.readAsDataURL(file);}
window.saveProfile=async function(){if(!currentProfile)currentProfile=defaultProfile();currentProfile.name=val("pname");currentProfile.age=val("page");currentProfile.bio=val("pbio");currentProfile.emailVerified=currentUser.emailVerified;currentProfile.interests=Array.from(document.querySelectorAll(".chip-check input:checked")).map(x=>x.value);currentProfile.profileComplete=Boolean(currentProfile.name&&currentProfile.photo&&currentProfile.interests.length>0);currentProfile.updatedAt=Date.now();await saveProfileToFirebase();if(!currentProfile.profileComplete){toast("Inserisci nome, foto e almeno un interesse");return;}toast("Profilo salvato");await updateMyLocation(false);await loadNearbyUsers();showView("home");}
window.verifyPhoto=async function(){if(!currentProfile)currentProfile=defaultProfile();currentProfile.verified=true;await saveProfileToFirebase();toast("Verifica foto simulata");render();}
function stickersView(){return `<h2 class="section-title">Sticker</h2><div class="grid3">${stickers.map(s=>`<button class="sticker"><span class="emoji">${s[0]}</span>${s[1]}</button>`).join("")}</div>`;}
window.sendSticker=async function(toUid,text){await addDoc(collection(db,"messages"),{from:currentUser.uid,to:toUid,text:"Sticker: "+text,createdAt:serverTimestamp()});toast("Sticker inviato");}
function chatView(){const myMsgs=messages.filter(m=>m.from===currentUser.uid||m.to===currentUser.uid||m.to==="global");return `<h2 class="section-title">Chat</h2><div class="card">${myMsgs.length?myMsgs.map(m=>`<div class="msg ${m.from===currentUser.uid?"me":""}">${esc(m.text)}</div>`).join(""):`<p class="bio">Nessun messaggio.</p>`}<input class="input" id="chatText" placeholder="Messaggio demo globale"><button class="btn primary" onclick="sendGlobalMsg()">Invia demo</button></div>`;}
window.sendGlobalMsg=async function(){const text=val("chatText");if(!text)return;await addDoc(collection(db,"messages"),{from:currentUser.uid,to:"global",text,createdAt:serverTimestamp()});await loadMessages();render();}
function menuView(){return `<h2 class="section-title">Menu</h2><div class="grid2"><button class="btn" onclick="showView('profile')">👤 Profilo</button><button class="btn" onclick="refreshLocation()">📍 Aggiorna GPS</button><button class="btn" onclick="toggleVisibility()">👻 Visibile/Invisibile</button><button class="btn danger" onclick="authBtn.click()">🚪 Esci</button></div><p class="notice">Gli sticker sono inviti simbolici. Nessuno è obbligato a rispondere.</p>`;}
window.refreshLocation=async()=>await updateMyLocation(true);
window.toggleVisibility=async function(){if(!currentProfile)return;currentProfile.visible=!currentProfile.visible;await saveProfileToFirebase();toast(currentProfile.visible?"Ora sei visibile":"Ora sei invisibile");}
function val(id){return document.getElementById(id)?.value?.trim()||"";}
function getDistanceMeters(lat1,lon1,lat2,lon2){const R=6371000,toRad=d=>d*Math.PI/180,dLat=toRad(lat2-lat1),dLon=toRad(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function cleanError(msg){return String(msg).replace("Firebase: ","").replace("Error ","").replace("(auth/","").replace(").","");}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",3500);}
function esc(str){return String(str||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
render();
